name: CI/CD

on:
  push:
    branches: master
    tags: v*
  pull_request:
    branches: master
  schedule:
    - cron: '0 12 * * 6'

jobs:

  test:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30
    strategy:
      matrix:
        go:
          - '^1.16'
          - '^1.17'
          - 'tip'

    steps:
      - uses: actions/setup-go@v3.1.0
        if: matrix.go != 'tip'
        with:
          go-version: ${{ matrix.go }}

      - name: Install Go tip
        if: matrix.go == 'tip'
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          ./make.bash
          echo "GOROOT=$HOME/gotip" >> $GITHUB_ENV
          echo "$HOME/gotip/bin" >> $GITHUB_PATH

      - run: go version

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/bin
            ~/go/pkg
            ~/go/src
            ~/.cache/go-build
            ~/.cache/golangci-lint
            .gobincache
          key: v3-test-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            v3-test-${{ runner.os }}-

      - run: cd build/tools && go generate
      - run: .gobincache/golangci-lint run
      - run: go test -race ./...

      - name: Report code coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        if: env.COVERALLS_TOKEN
        run: .gobincache/goveralls -service=GitHub
